### ISSUE TITLE
Webrtc demo is not working for android OS 7.0 (API level 24)

### ISSUE THREAD

**Issue by JeetSA** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#17] opened 2020-03-05 11:27 UTC
Hello

I am using webrtc demo for video streaming and it is working fine on android 8 and above. However when I am trying to run the same demo in android version 7.0, it is giving me error as follow:

> javax.websocket.DeploymentException: SSL handshake has failed

The device details are as follow:

- Device name: Samsung Galaxy J7 Prime
- OS version: 7.0

Can you please help me with this?

Thanks

**Comment by zhiyua-git** [comment] 2020-03-05 20:16
Hi @JeetSA ,

We don't have Samsung Galaxy J7 Prime now, can you provide the stacktrace of the failure? The failure is likely caused by Tyrus websocket client we use to talk to KVS signaling backend, but you can also try to replace Tyrus with OkHttp to see if that helps on your device. Thanks.

**Comment by JeetSA** [comment] 2020-03-06 06:20
Hello @zhiyua-git 

Thanks for replying.

Here is the stacktrace for the error which I am getting.
 

> org.awaitility.core.ConditionTimeoutException: Condition com.amazonaws.kinesisvideo.signaling.tyrus.WebSocketClient$3 was not fulfilled within 10 seconds.

I am trying to replace Tyrus with OkHttp as you suggested.
Thanks.

**Comment by mrArtCore** [comment] 2020-06-13 08:38
> Hi @JeetSA ,
> 
> We don't have Samsung Galaxy J7 Prime now, can you provide the stacktrace of the failure? The failure is likely caused by Tyrus websocket client we use to talk to KVS signaling backend, but you can also try to replace Tyrus with OkHttp to see if that helps on your device. Thanks.

You can try any Android 7 device and you will see that it's just not working.
I wish I saw this Issue earlier =(((

**Comment by MushMal** [comment] 2020-09-25 18:58
Not sure how actionable this is. Resolving for now.

**Closed by MushMal** 2020-09-25 18:58 UTC
