### ISSUE TITLE
please help me with multiviewer support

### ISSUE THREAD

**Issue by ranjanpucsd** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-android#20] opened 2020-04-17 18:35 UTC
app is not working for more than one viewer .i need multi-viewer support .
**in readme file Optionally, when using it in viewer mode, you can enter a unique Client Id . Client ID is required only if multiple viewers are connected to a channel. This helps channel's master identify respective viewers.** 
I couldn't understand above line.
 please help me thanks in advance.

**Comment by aragorntheking** [comment] 2020-05-14 13:38
I am facing the same issue. The demo does not seem to work for multiple viewers connecting to the same channel even when different client Ids are provided. As soon as the 2nd client is connected, both the viewers stops receiving any frames

**Comment by varun27wahi** [comment] 2020-06-04 17:45
Same issue for me. There's no documentation other than sample app which we can refer to.

**Comment by varun27wahi** [comment] 2020-06-11 00:37
So I got it to work. The sample app is designed for 1:1 communication. AS soon as as new viewer connects to the master, the remote description for the master changes and the old connection lost. 
To solve this, I created a HashMap for the master to store all connections. Whenever the master received an offer from a new viewer, I created a new entry in the HashMap, so that each new connection is unique.

**Comment by jeryini** [comment] 2020-07-30 18:43
Hello @varun27wahi !

Care to share your code fix here? It would be greatly appreciated!

**Comment by varun27wahi** [comment] 2020-07-30 19:34
Hi @jeryini!

Unfortunately I can't share the code since it is not a personal project. I can give you a basic overview of what I did and you can reach out me if you still have doubts.

I basically replaced the single `PeerConnection localPeer` member with a `HashMap<String, PeerConnection>`, where the key is a viewer's client ID. Then whenever a new offer comes in, create a new entry in the map. Rest of the process is same as what's done in the existing code. Hope this helps!

**Comment by jeryini** [comment] 2020-08-01 07:59
Hi @varun27wahi!

Thank you for your explanation. Will try to reproduce your solution.

**Comment by MushMal** [comment] 2020-09-25 18:57
Closing this for now. The sample is not designed to fully support the multi-client.

**Closed by MushMal** 2020-09-25 18:57 UTC

**Comment by nikinci** [comment] 2021-07-06 18:22
Hi @jeryini Did you apply the solution? Can you share the code if you fixed the  problem?

**Comment by gvickygvignesh** [comment] 2022-03-03 05:39
Hi. Does anyone update the code with multiviewer support? Any sample for the same?
